/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef OBJECTS_H
#define OBJECTS_H

/* function declarations */
void init_objects(void);
Netsnmp_Node_Handler handle_loginString;
Netsnmp_Node_Handler handle_dateString;
Netsnmp_Node_Handler handle_integer;
Netsnmp_Node_Handler handle_sysInfo;

#endif /* OBJECTS_H */
